// Code generated by mockery v1.0.0. DO NOT EDIT.

package storagemocks

import (
	context "context"

	storage "github.com/gavrilaf/jorel/pkg/scheduler/storage"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *Handler) HandleMessage(ctx context.Context, msg storage.ScheduledMessage) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.ScheduledMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
