// Code generated by mockery v1.0.0. DO NOT EDIT.

package schedulermocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TimeSource is an autogenerated mock type for the TimeSource type
type TimeSource struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *TimeSource) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
